export const PLC_LATEST_POLL_MS = Number(import.meta.env.VITE_PLC_LATEST_POLL_MS || 5000);

export const MACHINE_NAMES = {};

export const DEFAULT_MACHINES = [];

export function getMachineKey(machine = {}) {
  return machine.key || machine.machine_key || machine.ip;
}

const machineNameCollator = new Intl.Collator(undefined, {
  numeric: true,
  sensitivity: "base",
});

function getMachineLabel(machine = {}) {
  return machine.name || MACHINE_NAMES[machine.ip] || machine.machine_name || getMachineKey(machine) || machine.ip || "";
}

function getMachineSortParts(machine = {}) {
  const label = getMachineLabel(machine);
  const normalized = String(label || "")
    .trim()
    .replace(/\s+/g, " ")
    .replace(/\s*-\s*/g, "-")
    .replace(/([a-z])\s+(\d)/gi, "$1$2")
    .replace(/(\d)\s+([a-z])/gi, "$1$2");
  const match = normalized.match(/^(.*?)(?:-?\s*0*(\d+))$/);
  return {
    family: match ? match[1].replace(/[-\s]+$/g, "") : normalized,
    number: match ? Number(match[2]) : Number.MAX_SAFE_INTEGER,
    label: normalized,
  };
}

export function sortMachinesBySeries(source = []) {
  return [...source].sort((a, b) => {
    const aParts = getMachineSortParts(a);
    const bParts = getMachineSortParts(b);
    const familyDiff = machineNameCollator.compare(aParts.family, bParts.family);
    if (familyDiff !== 0) return familyDiff;
    if (aParts.number !== bParts.number) return aParts.number - bParts.number;
    return machineNameCollator.compare(aParts.label, bParts.label);
  });
}

export function mergeMachineList(list = []) {
  const byKey = new Map(DEFAULT_MACHINES.map((machine) => [getMachineKey(machine), machine]));
  list.forEach((machine) => {
    const key = getMachineKey(machine);
    const defaultMachine = byKey.get(key);
    byKey.set(key, {
      ...(defaultMachine || {}),
      ...machine,
      connected: machine.connected,
      error: machine.error,
      lastCycleAt: machine.lastCycleAt,
      lastShotNumber: machine.lastShotNumber,
      partName: machine.partName,
      cycleTime: machine.cycleTime,
    });
  });
  return sortMachinesBySeries(Array.from(byKey.values()));
}

export const REGISTER_GROUPS = [
  {
    id: "production",
    label: "Production",
    kind: "ube",
    icon: "TIME",
    color: "#22d3ee",
    keys: [
      { name: "machine_name", unit: "" },
      { name: "plc_ip", unit: "" },
      { name: "part_name", unit: "" },
      { name: "shot_date", unit: "" },
      { name: "shot_time", unit: "" },
      { name: "shot_datetime", unit: "" },
      { name: "shot_year", unit: "" },
      { name: "shot_month", unit: "" },
      { name: "shot_day", unit: "" },
      { name: "shot_hour", unit: "" },
      { name: "shot_minute", unit: "" },
      { name: "shot_second", unit: "" },
      { name: "shot_number", unit: "" },
      { name: "cycle_time", unit: "sec" },
      { name: "minor_stoppage", unit: "sec" },
    ],
  },
  {
    id: "cycle_times",
    label: "Cycle Timings",
    kind: "ube",
    icon: "CYC",
    color: "#f97316",
    keys: [
      { name: "die_close_core_in_time", unit: "sec" },
      { name: "pouring_time", unit: "sec" },
      { name: "shot_fwd_time", unit: "sec" },
      { name: "curing_time", unit: "sec" },
      { name: "die_open_core_out_time", unit: "sec" },
      { name: "ejector_time", unit: "sec" },
      { name: "extract_time", unit: "sec" },
      { name: "spray_time", unit: "sec" },
    ],
  },
  {
    id: "shot",
    label: "Shot Setup",
    kind: "ube",
    icon: "SPD",
    color: "#a78bfa",
    keys: [
      { name: "v1_speed", unit: "m/sec" },
      { name: "v2_speed", unit: "m/sec" },
      { name: "v3_speed", unit: "m/sec" },
      { name: "v4_speed", unit: "m/sec" },
      { name: "accel_point", unit: "mm" },
      { name: "deaccel_point", unit: "mm" },
      { name: "intensification_time", unit: "msec" },
      { name: "biscuit_thickness", unit: "mm" },
    ],
  },
  {
    id: "pressure",
    label: "Pressure & Tonnage",
    kind: "ube",
    icon: "TON",
    color: "#34d399",
    keys: [
      { name: "metal_pressure", unit: "MPa" },
      { name: "clamp_tonnage_he_low_pct", unit: "%" },
      { name: "clamp_tonnage_he_low_mn", unit: "MN" },
      { name: "clamp_tonnage_op_up_pct", unit: "%" },
      { name: "clamp_tonnage_op_low_pct", unit: "%" },
      { name: "clamp_tonnage_he_up_pct", unit: "%" },
      { name: "clamp_force_pct", unit: "%" },
      { name: "clamp_tonnage", unit: "T" },
      { name: "shot_acc_pressure", unit: "MPa" },
      { name: "intensification_acc_pressure", unit: "MPa" },
      { name: "jet_cooling_pressure", unit: "kgf/cm2" },
      { name: "vacuum_pressure", unit: "mbar" },
    ],
  },
  {
    id: "temp",
    label: "Temperature & Flow",
    kind: "ube",
    icon: "TMP",
    color: "#f472b6",
    keys: [
      { name: "cooling_water_mov", unit: "L/min" },
      { name: "cooling_water_sta", unit: "L/min" },
      { name: "furnace_metal_temp", unit: "°C" },
      { name: "fixed_die_temp_f1", unit: "°C" },
      { name: "fixed_die_temp_f2", unit: "°C" },
      { name: "moving_die_temp_m1", unit: "°C" },
      { name: "moving_die_temp_m2", unit: "°C" },
      { name: "slide_temp_s1", unit: "°C" },
    ],
  },
  {
    id: "machine_bits",
    label: "Machine Bits",
    kind: "ube",
    icon: "STS",
    color: "#60a5fa",
    keys: [
      { name: "running_mode", unit: "" },
      { name: "emergency_stop", unit: "" },
      { name: "hyd_pump_motor_overload", unit: "" },
      { name: "hyd_oil_level_low", unit: "" },
      { name: "hyd_oil_high_temp", unit: "" },
      { name: "servo_pump_overload", unit: "" },
      { name: "servo_pump_motor_high_temp", unit: "" },
      { name: "die_close_step", unit: "" },
      { name: "pouring_step", unit: "" },
      { name: "shot_fwd_step", unit: "" },
      { name: "curing_step", unit: "" },
      { name: "die_open_step", unit: "" },
      { name: "ejector_step", unit: "" },
      { name: "extractor_step", unit: "" },
      { name: "spray_step", unit: "" },
      { name: "cycle_end", unit: "" },
    ],
  },
  {
    id: "leak_test",
    label: "Leak Test",
    kind: "leaktest",
    icon: "LT",
    color: "#14b8a6",
    keys: [
      { name: "machine", unit: "" },
      { name: "ip", unit: "" },
      { name: "status", unit: "" },
      { name: "cycle_end_time", unit: "" },
      { name: "part_qr_code", unit: "" },
      { name: "result", unit: "" },
      { name: "body_leak_value", unit: "" },
      { name: "gall_1", unit: "" },
      { name: "gall_2", unit: "" },
      { name: "cycle_time", unit: "sec" },
      { name: "running_mode", unit: "" },
      { name: "manual", unit: "" },
      { name: "dry", unit: "" },
      { name: "wey", unit: "" },
      { name: "both", unit: "" },
    ],
  },
];

export const PARAMETER_NAMES = REGISTER_GROUPS.flatMap((group) => group.keys.map((item) => item.name));
export const PARAMETER_NAMES_BY_KIND = REGISTER_GROUPS.reduce((acc, group) => {
  acc[group.kind] = acc[group.kind] || new Set();
  group.keys.forEach((item) => acc[group.kind].add(item.name));
  return acc;
}, {});
export const HIDDEN_DB_FIELDS = new Set([
  "id",
  "created_at",
  "raw_readings_json",
  "shot_uid",
  "rn",
  "is_online",
  "has_data",
  "error",
  "db_status",
  "Counter",
  "HIGH SHOT COUNT value",
  "NG COUNTER value",
  "high_shot_count",
  "high_shot",
  "ng_counter",
  "off_shot",
  "Sr. No",
  "cycletime EndDateTime",
  "AUTO/OK-step value (sec)",
  "AUTO/ROBOT/OK-step value (sec)",
  "SHOT FWD TIME sec value",
  "cycletime value (sec)",
  "DIE CLOSE/CORE IN -step value (sec)",
  "POURING -step value (sec)",
  "SHOT FWD -step value (sec)",
  "COOLING -step value (sec)",
  "DIE OPEN/CORE OUT -step value (sec)",
  "EXTRACTOR -step value (sec)",
  "EJECTOR -step value (sec)",
  "SPRAY -step value (sec)",
  "V1 m/sec value",
  "V2 m/sec) value",
  "V3 m/sec value",
  "V4 m/sec value",
  "ACCEL. POINT mm value",
  "DEACEL. POINT mm value",
  "METAL PRESS. Mpa value",
  "INTEN. TIME msec value",
  "BISCUIT THICKNESS mm value",
  "CLAMP TONNAGE(HE.LOW) % value",
  "CLAMP TONNAGE(HE.LOW) MN value",
  "CLAMP TONNAGE(OP.UP) % value",
  "CLAMP TONNAGE(OP.LOW) % value",
  "CLAMP TONNAGE(HE.UP) % value",
  "VACUUM PRESSURE mbar value",
  "COOLING WATER FLOW RATE(MOV.) L/min value",
  "COOLING WATER FLOW RATE(STA.) L/min value",
  "FURNACE METAL TEMP. C value",
  "DIE-CLOSE CORE IN TIME sec value",
  "POURING TIME sec value",
  "CURING TIME sec value",
  "DIE OPEN CORE OUT TIME sec value",
  "EJECTOR TIME sec value",
  "EXTRACT TIME sec value",
  "SPRAY TIME sec value",
  "CLAMP FORCE (%) value",
  "CLAMP TONNAGE (T) value",
  "SHOT ACC. PRESSURE MPa value",
  "INTENSIFICATION ACC. PRESSURE MPa value",
  "JET COOLING PRESSURE kgf/cm2 value",
  "FIXED DIE TEMP (F-1) C value",
  "FIXED DIE TEMP (F-2) C value",
  "MOVING DIE TEMP (M-1) C value",
  "MOVING DIE TEMP (M-2) C value",
  "SLIDE TEMP-1 (S-1) C value",
  "MANUAL MODE -step value (sec)",
  "EMG. STOP -step value (sec)",
  "HYD.OIL LEVEL LOW LIMIT -step value (sec)",
  "Running Mode (AUTO/ROBOT)",
  "EMG. STOP",
  "MANUAL MODE",
  "HYD. PUMP MOTOR OVERLOAD",
  "HYD. OIL LEVEL LOW LIMIT",
  "HYD. OIL HIGH TEMP.",
  "SERVO PUMP OVERLOAD",
  "SERVO PUMP MOTOR HIGH TEMP.",
  "DIE CLOSE / CORE IN - step",
  "POURING - step",
  "SHOT FWD - step",
  "CURING - step",
  "DIE OPEN / CORE OUT - step",
  "EJECTOR - step",
  "EXTRACTOR - step",
  "SPRAY - step",
  "Cycle End",
  "machine_key",
  "scan_data",
  "cycle_start",
  "auto_mode",
  "manual_mode",
  "ng_shot",
  "dry_mode",
  "wey_mode",
  "both_mode",
]);
export const DISPLAY_LABELS = {
  recorded_at: "Recorded At",
  machine_name: "Machine",
  plc_ip: "PLC IP",
  plc_port: "PLC Port",
  machine: "Machine",
  ip: "IP",
  status: "Status",
  cycle_end_time: "Cycle End Time",
  machine_key: "Machine Key",
  part_name: "Part Name",
  part_qr_code: "Part QR Code",
  body_leak_value: "Body Leak Value",
  gall_1: "GALL-1",
  gall_2: "GALL-2",
  result: "Result",
  manual: "Manual",
  dry_mode: "Dry",
  dry: "Dry",
  wey: "Wey",
  both: "Both",
  shot_year: "Shot Year",
  shot_month: "Shot Month",
  shot_day: "Shot Day",
  shot_date: "Shot Date",
  shot_time: "Shot Time",
  shot_datetime: "Shot Date Time",
  ok_shot: "OK Shot",
  shot_number: "Shot Number",
  cycle_time: "Cycle Time",
  minor_stoppage: "Minor Stoppage",
  minor_stoppage_machine: "Minor Stoppage Machine",
  "cycletime value (sec)": "Cycle Time",
  "cycletime EndDateTime": "Shot Time",
  shot_hour: "Shot Hour",
  shot_minute: "Shot Minute",
  shot_second: "Shot Second",
  die_close_core_in_time: "Die Close/Core In Time",
  pouring_time: "Pouring Time",
  shot_fwd_time: "Shot FWD Time",
  curing_time: "Curing Time",
  die_open_core_out_time: "Die Open/Core Out Time",
  ejector_time: "Ejector Time",
  extract_time: "Extractor Time",
  spray_time: "Spray Time",
  v1_speed: "V1 Speed",
  v2_speed: "V2 Speed",
  v3_speed: "V3 Speed",
  v4_speed: "V4 Speed",
  accel_point: "Accel. Point",
  deaccel_point: "Deaccel. Point",
  intensification_time: "Intensification Time",
  biscuit_thickness: "Biscuit Thickness",
  metal_pressure: "Metal Pressure",
  furnace_metal_temp: "Furnace Metal Temp",
  cooling_water_mov: "Water Flow MOV",
  cooling_water_sta: "Water Flow STA",
  clamp_tonnage_he_low_pct: "Clamp Tonnage HE Low %",
  clamp_tonnage_he_low_mn: "Clamp Tonnage HE Low MN",
  clamp_tonnage_op_up_pct: "Clamp Tonnage OP Up %",
  clamp_tonnage_op_low_pct: "Clamp Tonnage OP Low %",
  clamp_tonnage_he_up_pct: "Clamp Tonnage HE Up %",
  vacuum_pressure: "Vacuum Pressure",
  clamp_force_pct: "Clamp Force",
  clamp_tonnage: "Clamp Tonnage",
  shot_acc_pressure: "Shot Acc. Pressure",
  intensification_acc_pressure: "Intensification Acc. Pressure",
  jet_cooling_pressure: "Jet Cooling Pressure",
  fixed_die_temp_f1: "Fixed Die Temp F1",
  fixed_die_temp_f2: "Fixed Die Temp F2",
  moving_die_temp_m1: "Moving Die Temp M1",
  moving_die_temp_m2: "Moving Die Temp M2",
  slide_temp_s1: "Slide Temp S1",
  running_mode: "Running Mode",
  emergency_stop: "Emergency Stop",
  hyd_pump_motor_overload: "Hyd. Pump Motor Overload",
  hyd_oil_level_low: "Hyd. Oil Level Low",
  hyd_oil_high_temp: "Hyd. Oil High Temp",
  servo_pump_overload: "Servo Pump Overload",
  servo_pump_motor_high_temp: "Servo Pump Motor High Temp",
  die_close_step: "Die Close/Core In Step",
  pouring_step: "Pouring Step",
  shot_fwd_step: "Shot FWD Step",
  curing_step: "Curing Step",
  die_open_step: "Die Open Step",
  ejector_step: "Ejector Step",
  extractor_step: "Extractor Step",
  spray_step: "Spray Step",
  cycle_end: "Cycle End",
};

